version: '3.8' # Specify the Docker Compose file format version

services:
  backend:
    # Build context points to the current directory (where docker-compose.yml is),
    # because your backend's Dockerfile, main.py, etc., are directly here.
    build: .
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    volumes: # Optional: for development, mount code so changes are reflected without rebuilding
      - .:/app # Mount the current directory (ONYE-AI-FHIR) into /app in the container
    environment:
      # This ensures Flask knows the correct entry point.
      - FLASK_APP=main.py # IMPORTANT: Confirm your main Flask file is indeed main.py
      # - FLASK_ENV=development # Good for seeing debug messages in Flask container logs

  frontend:
    build: ./frontend # Build context for the frontend Dockerfile (relative to docker-compose.yml)
    ports:
      - "3000:3000" # Map host port 3000 to container port 3000
    volumes: # Optional: for development, mount code so changes are reflected without rebuilding
      - ./frontend:/app
    depends_on:
      - backend # Ensures the backend container starts before the frontend container
    # environment: # Optional: if you need to pass environment variables to Next.js at runtime
    #   - NEXT_PUBLIC_BACKEND_URL=http://backend:5000 # Use 'backend' (service name) as hostname